do not set scope.Start when start_instruction is null
 - this gets us to the original state how scope start was handled
   before
   https://github.com/jbevain/cecil/commit/7c8e0f767d7b2f652a430e4e26f1d98a20f9e125

 - fixes #57889

 - without this change we get excpetion when writing mdb like this:

    The "LinkAssemblies" task failed unexpectedly. [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
    System.NotSupportedException: Specified method is not supported. [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Cil.InstructionOffset.get_Offset() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.WriteScope(ScopeDebugInformation scope, MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.WriteScopes(Collection`1 scopes, MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.WriteScope(ScopeDebugInformation scope, MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.WriteScopes(Collection`1 scopes, MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.WriteRootScope(ScopeDebugInformation scope, MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Mdb.MdbWriter.Write(MethodDebugInformation info) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.AddTypes() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.BuildTypes() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.BuildModule() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.MetadataBuilder.BuildMetadata() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleWriter.<>c.b__2_0(MetadataBuilder builder, MetadataReader _) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Linker.Steps.BaseStep.Process(LinkContext context) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Mono.Linker.Pipeline.Process(LinkContext context) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res) [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Xamarin.Android.Tasks.LinkAssemblies.Execute() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]
       at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() [C:\xms\xamarin-forms-samples\Templates\DataTemplateSelector\Droid\Selector.Droid.csproj]